package support.kirimwa;

import fungsi.batasInput;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class DlgKirimWA extends javax.swing.JDialog {

    private final sekuel Sequel = new sekuel();
    private final validasi Valid = new validasi();
    private final SimpleDateFormat df = new SimpleDateFormat("HH:mm:ss");
    private String asal = "";
    
    public DlgKirimWA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        TNoWA.setDocument(new batasInput((byte) 15).getOnlyAngka(TNoWA));
        TIsiPesan.setDocument(new batasInput((int) 3000).getKata(TIsiPesan));
        jam();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        BtnTutup = new widget.Button();
        BtnKirim = new widget.Button();
        jLabel1 = new widget.Label();
        Tgl = new widget.Tanggal();
        TNoWA = new widget.TextBox();
        Jam = new widget.ComboBox();
        Menit = new widget.ComboBox();
        Detik = new widget.ComboBox();
        TNoRM = new widget.TextBox();
        TNm = new widget.TextBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TIsiPesan = new widget.TextArea();
        jLabel2 = new widget.Label();
        jLabel3 = new widget.Label();
        ChkJln = new widget.CekBox();
        jLabel4 = new widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setUndecorated(true);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Kirim Pesan via WA ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(514, 350));
        internalFrame1.setLayout(null);

        BtnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnTutup.setMnemonic('U');
        BtnTutup.setText("Tutup");
        BtnTutup.setToolTipText("Alt+U");
        BtnTutup.setNextFocusableComponent(TNoRM);
        BtnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTutupActionPerformed(evt);
            }
        });
        internalFrame1.add(BtnTutup);
        BtnTutup.setBounds(388, 302, 100, 30);

        BtnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnKirim.setMnemonic('S');
        BtnKirim.setText("Simpan");
        BtnKirim.setToolTipText("Alt+S");
        BtnKirim.setNextFocusableComponent(BtnTutup);
        BtnKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKirimActionPerformed(evt);
            }
        });
        BtnKirim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKirimKeyPressed(evt);
            }
        });
        internalFrame1.add(BtnKirim);
        BtnKirim.setBounds(20, 302, 100, 30);

        jLabel1.setText("Pasien :");
        internalFrame1.add(jLabel1);
        jLabel1.setBounds(0, 32, 80, 23);

        Tgl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "18-12-2024" }));
        Tgl.setDisplayFormat("dd-MM-yyyy");
        Tgl.setNextFocusableComponent(Jam);
        Tgl.setOpaque(false);
        Tgl.setPreferredSize(new java.awt.Dimension(95, 23));
        internalFrame1.add(Tgl);
        Tgl.setBounds(84, 62, 100, 23);

        TNoWA.setNextFocusableComponent(TIsiPesan);
        internalFrame1.add(TNoWA);
        TNoWA.setBounds(84, 92, 190, 24);

        Jam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        Jam.setNextFocusableComponent(Menit);
        internalFrame1.add(Jam);
        Jam.setBounds(188, 62, 62, 23);

        Menit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        Menit.setNextFocusableComponent(Detik);
        internalFrame1.add(Menit);
        Menit.setBounds(254, 62, 62, 23);

        Detik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        Detik.setNextFocusableComponent(ChkJln);
        internalFrame1.add(Detik);
        Detik.setBounds(320, 62, 62, 23);

        TNoRM.setEditable(false);
        TNoRM.setNextFocusableComponent(TNm);
        internalFrame1.add(TNoRM);
        TNoRM.setBounds(84, 32, 120, 24);

        TNm.setEditable(false);
        TNm.setNextFocusableComponent(Tgl);
        internalFrame1.add(TNm);
        TNm.setBounds(208, 32, 280, 24);

        TIsiPesan.setColumns(20);
        TIsiPesan.setRows(5);
        TIsiPesan.setNextFocusableComponent(BtnKirim);
        jScrollPane1.setViewportView(TIsiPesan);

        internalFrame1.add(jScrollPane1);
        jScrollPane1.setBounds(84, 122, 404, 174);

        jLabel2.setText("No. WA :");
        internalFrame1.add(jLabel2);
        jLabel2.setBounds(0, 92, 80, 23);

        jLabel3.setText("Tgl. / Jam :");
        internalFrame1.add(jLabel3);
        jLabel3.setBounds(0, 62, 80, 23);

        ChkJln.setBorder(null);
        ChkJln.setSelected(true);
        ChkJln.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ChkJln.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChkJln.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ChkJln.setNextFocusableComponent(TNoWA);
        internalFrame1.add(ChkJln);
        ChkJln.setBounds(386, 62, 28, 23);

        jLabel4.setText("Pesan :");
        internalFrame1.add(jLabel4);
        jLabel4.setBounds(0, 122, 80, 23);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKirimActionPerformed
        if (TNoRM.getText().isBlank() || TNm.getText().isBlank() || TIsiPesan.getText().isBlank()) {
            Valid.textKosong(TNoRM, "Data Pasien");
        } else if (TNoWA.getText().isBlank()) {
            Valid.textKosong(TNoWA, "No. WA");
        } else if (TIsiPesan.getText().isBlank()) {
            Valid.textKosong(TIsiPesan, "Isi pesan");
        } else {
            if (JOptionPane.showConfirmDialog(null, "Eeiittss... Udah benar data WA yang mau dikirim?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (KoneksiDBWA.kirimPesanWA(TNoWA.getText(), TIsiPesan.getText(), Valid.getTglJamSmc(Tgl, Jam, Menit, Detik), asal)) {
                    JOptionPane.showMessageDialog(null, "Pesan berhasil disimpan!\nPesan akan segera dikirim ke pasien via WA.");
                    BtnTutupActionPerformed(null);
                }
            }
        }
    }//GEN-LAST:event_BtnKirimActionPerformed

    private void BtnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTutupActionPerformed
        emptTeks();
        dispose();
    }//GEN-LAST:event_BtnTutupActionPerformed

    private void BtnKirimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKirimKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnKirimActionPerformed(null);
        }
    }//GEN-LAST:event_BtnKirimKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgKirimWA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgKirimWA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgKirimWA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgKirimWA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgKirimWA dialog = new DlgKirimWA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKirim;
    private widget.Button BtnTutup;
    private widget.CekBox ChkJln;
    private widget.ComboBox Detik;
    private widget.ComboBox Jam;
    private widget.ComboBox Menit;
    private widget.TextArea TIsiPesan;
    private widget.TextBox TNm;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoWA;
    private widget.Tanggal Tgl;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel1;
    private widget.Label jLabel2;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void setRM(String norm, String namapasien, String nohp, String pesan, String asal) {
        TNoRM.setText(norm);
        TNm.setText(namapasien);
        TNoWA.setText(nohp);
        TIsiPesan.setText(pesan);
        this.asal = asal;
        ChkJln.setSelected(true);
    }
    
    public void setRM(String norm, String namapasien, String nohp, String asal) {
        setRM(norm, namapasien, nohp, "", asal);
    }
    
    public void setRM(String norm, String namapasien, String asal) {
        setRM(norm, namapasien, Sequel.cariIsiSmc("select pasien.no_tlp from pasien where pasien.no_rkm_medis = ?", norm), asal);
    }
    
    private void jam() {
        ActionListener taskPerformer = (ActionEvent e) -> {
            Date now = Calendar.getInstance().getTime();
            if (ChkJln.isSelected()) {
                String jam = df.format(now);
                
                Tgl.setDate(now);
                Jam.setSelectedItem(jam.substring(0, 2));
                Menit.setSelectedItem(jam.substring(3, 5));
                Detik.setSelectedItem(jam.substring(6, 8));
            }
        };
        
        new Timer(1000, taskPerformer).start();
    }
    
    private void emptTeks() {
        TNoRM.setText("");
        TNm.setText("");
        TNoWA.setText("");
        TIsiPesan.setText("");
        this.asal = "";
        ChkJln.setSelected(false);
    }
}
