
/*
 * Kontribusi Oleh Ferry Ardiansyah - RSIAP 3326051
 *
 * Created on May 22, 2010, 11:58:21 PM
 */
package bridging;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.WarnaTable;
import fungsi.akses;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;

/**
 *
 * @author dosen
 */
public final class BPJSAntreanPerKodebooking extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private final SimpleDateFormat dtf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private validasi Valid = new validasi();
    private sekuel Sequel = new sekuel();
    private ApiMobileJKN api = new ApiMobileJKN();
    private String URL = "", link = "", utc = "";
    private HttpHeaders headers;
    private HttpEntity requestEntity;
    private ObjectMapper mapper = new ObjectMapper();
    private JsonNode root;
    private JsonNode nameNode;
    private JsonNode response;

    /**
     * Creates new form DlgJnsPerawatanRalan
     *
     * @param parent
     * @param modal
     */
    public BPJSAntreanPerKodebooking(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(8, 1);
        setSize(628, 674);

        tabMode = new DefaultTableModel(null, new Object[] {"", "", ""}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbJnsPerawatan.setModel(tabMode);

        tbJnsPerawatan.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbJnsPerawatan.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (int i = 0; i < 3; i++) {
            TableColumn column = tbJnsPerawatan.getColumnModel().getColumn(i);
            if (i == 0) {
                column.setPreferredWidth(110);
            } else if (i == 1) {
                column.setPreferredWidth(30);
            } else if (i == 2) {
                column.setPreferredWidth(230);
            }
        }
        tbJnsPerawatan.setDefaultRenderer(Object.class, new WarnaTable());

        try {
            link = koneksiDB.URLAPIMOBILEJKN();
        } catch (Exception e) {
            System.out.println("E : " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbJnsPerawatan = new widget.Table();
        jPanel2 = new javax.swing.JPanel();
        panelGlass9 = new widget.panelisi();
        jLabel19 = new widget.Label();
        KodeBooking = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnPrint = new widget.Button();
        label1 = new widget.Label();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Antrean Per Kodebooking BPJS ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbJnsPerawatan.setToolTipText("Silahkan klik untuk memilih data yang mau diedit ataupun dihapus");
        tbJnsPerawatan.setName("tbJnsPerawatan"); // NOI18N
        Scroll.setViewportView(tbJnsPerawatan);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(44, 50));
        jPanel2.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass9.setName("panelGlass9"); // NOI18N
        panelGlass9.setPreferredSize(new java.awt.Dimension(44, 44));
        panelGlass9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel19.setText("kode Booking :");
        jLabel19.setName("jLabel19"); // NOI18N
        jLabel19.setPreferredSize(new java.awt.Dimension(90, 23));
        panelGlass9.add(jLabel19);

        KodeBooking.setName("KodeBooking"); // NOI18N
        KodeBooking.setPreferredSize(new java.awt.Dimension(200, 23));
        KodeBooking.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KodeBookingKeyPressed(evt);
            }
        });
        panelGlass9.add(KodeBooking);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('2');
        BtnCari.setToolTipText("Alt+2");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass9.add(BtnCari);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        panelGlass9.add(BtnPrint);

        label1.setText("                           ");
        label1.setName("label1"); // NOI18N
        panelGlass9.add(label1);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass9.add(BtnKeluar);

        jPanel2.add(panelGlass9, java.awt.BorderLayout.CENTER);

        internalFrame1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
        tampil();
}//GEN-LAST:event_BtnCariActionPerformed

    private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnCariActionPerformed(null);
        }
}//GEN-LAST:event_BtnCariKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            dispose();
        }
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        if (tabMode.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Maaf, data sudah habis. Tidak ada data yang bisa anda print...!!!!");
        } else if (tabMode.getRowCount() != 0) {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Sequel.deleteTemporary();
            for (int i = 0; i < tbJnsPerawatan.getRowCount(); i++) {
                Sequel.temporary(String.valueOf(i + 1),
                    (String) tabMode.getValueAt(i, 0),
                    (String) tabMode.getValueAt(i, 1),
                    (String) tabMode.getValueAt(i, 2)
                );
            }

            Map<String, Object> param = new HashMap<>();
            param.put("namars", akses.getnamars());
            param.put("alamatrs", akses.getalamatrs());
            param.put("kotars", akses.getkabupatenrs());
            param.put("propinsirs", akses.getpropinsirs());
            param.put("kontakrs", akses.getkontakrs());
            param.put("emailrs", akses.getemailrs());
            param.put("logo", Sequel.cariGambar("select setting.logo from setting"));
            Valid.reportTempSmc("rptBPJSAntreanPerKodebooking.jasper", "report", "::[ Antrean BPJS Per Kodebooking ]::", param);
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void KodeBookingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KodeBookingKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tampil();
            BtnPrint.requestFocus();
        }
    }//GEN-LAST:event_KodeBookingKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            BPJSAntreanPerKodebooking dialog = new BPJSAntreanPerKodebooking(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    private void emptTeks() {
        KodeBooking.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.TextBox KodeBooking;
    private widget.ScrollPane Scroll;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel19;
    private javax.swing.JPanel jPanel2;
    private widget.Label label1;
    private widget.panelisi panelGlass9;
    private widget.Table tbJnsPerawatan;
    // End of variables declaration//GEN-END:variables

    private void tampil() {
        Valid.tabelKosong(tabMode);
        try {
            headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.add("x-cons-id", koneksiDB.CONSIDAPIMOBILEJKN());
            utc = String.valueOf(api.GetUTCdatetimeAsString());
            headers.add("x-timestamp", utc);
            headers.add("x-signature", api.getHmac(utc));
            headers.add("user_key", koneksiDB.USERKEYAPIMOBILEJKN());
            requestEntity = new HttpEntity(headers);
            URL = link + "/antrean/pendaftaran/kodebooking/" + KodeBooking.getText();
            System.out.println("URL : " + URL);
            root = mapper.readTree(api.getRest().exchange(URL, HttpMethod.GET, requestEntity, String.class).getBody());
            nameNode = root.path("metadata");
            if (nameNode.path("code").asText().equals("200")) {
                response = mapper.readTree(api.Decrypt(root.path("response").asText(), utc));
                System.out.println("Response : " + response);
                if (response.isArray()) {
                    for (JsonNode list : response) {
                        if (list.has("kodebooking")) {
                            tabMode.addRow(new Object[] {
                                "Kode booking", ":",
                                list.path("kodebooking").asText()
                            });
                        }
                        if (list.has("tanggal")) {
                            tabMode.addRow(new Object[] {
                                "Tanggal", ":",
                                list.path("tanggal").asText()
                            });
                        }
                        if (list.has("kodepoli")) {
                            tabMode.addRow(new Object[] {
                                "Kode Poli", ":",
                                list.path("kodepoli").asText()
                            });
                            tabMode.addRow(new Object[] {
                                "Nama Poli", ":",
                                Sequel.cariIsiSmc("select nm_poli_bpjs from maping_poli_bpjs where kd_poli_bpjs = ?", list.path("kodepoli").asText())
                            });
                        }
                        if (list.has("kodedokter")) {
                            tabMode.addRow(new Object[] {
                                "Kode Dokter", ":",
                                list.path("kodedokter").asText()
                            });
                            tabMode.addRow(new Object[] {
                                "Nama Dokter", ":",
                                Sequel.cariIsiSmc("select nm_dokter_bpjs from maping_dokter_dpjpvclaim where kd_dokter_bpjs = ?", list.path("kodedokter").asText())
                            });
                        }
                        if (list.has("jampraktek")) {
                            tabMode.addRow(new Object[] {
                                "Jam Praktek", ":",
                                list.path("jampraktek").asText()
                            });
                        }
                        if (list.has("nik")) {
                            tabMode.addRow(new Object[] {
                                "NIK", ":",
                                list.path("nik").asText()
                            });
                        }
                        if (list.has("nokapst")) {
                            tabMode.addRow(new Object[] {
                                "No. Kartu Peserta", ":",
                                list.path("nokapst").asText()
                            });
                        }
                        if (list.has("nohp")) {
                            tabMode.addRow(new Object[] {
                                "No. HP", ":",
                                list.path("nohp").asText()
                            });
                        }
                        if (list.has("norekammedis")) {
                            tabMode.addRow(new Object[] {
                                "No. RM", ":",
                                list.path("norekammedis").asText()
                            });
                        }
                        if (list.has("jeniskunjungan")) {
                            tabMode.addRow(new Object[] {
                                "Jenis Kunjungan", ":",
                                list.path("jeniskunjungan").asText()
                            });
                        }
                        if (list.has("nomorreferensi")) {
                            tabMode.addRow(new Object[] {
                                "No. Referensi", ":",
                                list.path("nomorreferensi").asText()
                            });
                        }
                        if (list.has("sumberdata")) {
                            tabMode.addRow(new Object[] {
                                "Sumber Data", ":",
                                list.path("sumberdata").asText()
                            });
                        }
                        if (list.has("ispeserta")) {
                            tabMode.addRow(new Object[] {
                                "Peserta BPJS?", ":",
                                (list.path("ispeserta").asBoolean() ? "Ya" : "Tidak")
                            });
                        }
                        if (list.has("noantrean")) {
                            tabMode.addRow(new Object[] {
                                "No. Antrian", ":",
                                list.path("noantrean").asText()
                            });
                        }
                        if (list.has("estimasidilayani")) {
                            tabMode.addRow(new Object[] {
                                "Estimasi Dilayani", ":",
                                dtf.format(new Date(list.path("estimasidilayani").asLong()))
                            });
                        }
                        if (list.has("createdtime")) {
                            tabMode.addRow(new Object[] {
                                "Waktu Dibuat", ":",
                                dtf.format(new Date(list.path("createdtime").asLong()))
                            });
                        }
                        if (list.has("status")) {
                            tabMode.addRow(new Object[] {
                                "Status", ":",
                                list.path("status").asText()
                            });
                        }
                        tabMode.addRow(new Object[] {"", "", ""});
                    }
                }
            } else {
                System.out.println("Notif : " + nameNode.path("message").asText());
            }
        } catch (Exception e) {
            System.out.println("Notif : " + e);
        }
    }
    
    public void isCek() {
        
    }
}
